version: "3.9"

services:
  db:
    image: postgres:17.2
    container_name: db
    networks:
      - main
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

  app:
    build:
      context: .
    container_name: app
    image: app:1.0
    volumes:
      - .:/app/
    networks:
      - main
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

volumes:
  postgres_data:


networks:
  main:
