version: "3.9"

services:
  db:
    image: postgres:17.2
    container_name: db
    networks:
      - main
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

  app:
    build:
      context: .
    container_name: app
    image: app:1.0
    networks:
      - main
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

volumes:
  postgres_data:


networks:
  main:
