version: "3.9"

services:
  db:
    image: postgres:17.2
    container_name: db
    networks:
      - main
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

  app:
    build:
      context: .
    image: app:1.0
    container_name: app
    volumes:
      - .:/app/
      - static:/app/src/static
      - media:/app/src/media
    networks:
      - main
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

  pgadmin:
    image: dpage/pgadmin4:8.14
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5051:80"
    networks:
      - main
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    env_file:
      - .env

  nginx:
    image: nginx:1.27.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static:/var/www/static
      - media:/var/www/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - main
    depends_on:
      - app
      - db
    restart: always

volumes:
  static:
  media:
  postgres_data:

networks:
  main:
