version: "3.9"

services:
  db:
    image: postgres:17.2
    container_name: db
    networks:
      - main
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

  app:
    build:
      context: .
    image: app:1.0
    container_name: app
    volumes:
      - static:/app/src/static
      - media:/app/src/media
    networks:
      - main
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

  pgadmin:
    image: dpage/pgadmin4:8.14
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5051:80"
    networks:
      - main
    env_file:
      - .env

  nginx:
    image: nginx:1.27.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static:/var/www/static
      - media:/var/www/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - main
    depends_on:
      - app
      - db
    restart: always

volumes:
  static:
  media:
  postgres_data:

networks:
  main:
